package axhub

import (
    "reflect"
    "testing"
)

func TestGeneratedOperationFacadesCoverAllRoutes(t *testing.T) {
    c := NewClient(Config{})
    contexts := map[string]reflect.Type{
        "apps": reflect.TypeOf(c.Apps),
        "identity": reflect.TypeOf(c.Identity()),
        "tenants": reflect.TypeOf(c.Tenants()),
        "authz": reflect.TypeOf(c.Authz()),
        "audit": reflect.TypeOf(c.Audit()),
        "gateway": reflect.TypeOf(c.Gateway()),
        "data": reflect.TypeOf(c.Data()),
        "deployments": reflect.TypeOf(c.Deployments()),
        "notifications": reflect.TypeOf(c.Notifications()),
    }
    expected := []map[string]string{
        {"context": "identity", "go": "AuthGetWellKnownJwksJson"},
        {"context": "identity", "go": "AuthGetWellKnownOauthAuthorizationServer"},
        {"context": "identity", "go": "AuthGetWellKnownOpenidConfiguration"},
        {"context": "apps", "go": "AppsGetApiV1AccessRequests"},
        {"context": "apps", "go": "AppsPostApiV1AccessRequests"},
        {"context": "apps", "go": "AppsPatchApiV1AccessRequestsByIdApprove"},
        {"context": "apps", "go": "AppsPatchApiV1AccessRequestsByIdReject"},
        {"context": "notifications", "go": "NotificationsPostApiV1AppMails"},
        {"context": "notifications", "go": "NotificationsPostApiV1AppNotifications"},
        {"context": "apps", "go": "AppsDeleteApiV1AppsByAppID"},
        {"context": "apps", "go": "AppsGetApiV1AppsByAppID"},
        {"context": "apps", "go": "AppsPatchApiV1AppsByAppID"},
        {"context": "apps", "go": "AppsDeleteApiV1AppsByAppIDAccess"},
        {"context": "apps", "go": "AppsPostApiV1AppsByAppIDAccess"},
        {"context": "apps", "go": "AppsGetApiV1AppsByAppIDAccessMe"},
        {"context": "apps", "go": "AppsPostApiV1AppsByAppIDArchive"},
        {"context": "apps", "go": "AppsGetApiV1AppsByAppIDComments"},
        {"context": "apps", "go": "AppsPostApiV1AppsByAppIDComments"},
        {"context": "data", "go": "SchemaGetApiV1AppsByAppIDDbTables"},
        {"context": "data", "go": "SchemaGetApiV1AppsByAppIDDbTablesByTableRows"},
        {"context": "deployments", "go": "DeployGetApiV1AppsByAppIDDeployments"},
        {"context": "deployments", "go": "DeployPostApiV1AppsByAppIDDeployments"},
        {"context": "deployments", "go": "DeployGetApiV1AppsByAppIDDeploymentsByDid"},
        {"context": "deployments", "go": "DeployPostApiV1AppsByAppIDDeploymentsByDidCancel"},
        {"context": "deployments", "go": "DeployGetApiV1AppsByAppIDDeploymentsByDidDiagnoses"},
        {"context": "deployments", "go": "DeployPostApiV1AppsByAppIDDeploymentsByDidRollback"},
        {"context": "deployments", "go": "DeployGetApiV1AppsByAppIDDiagnosis"},
        {"context": "apps", "go": "AppsGetApiV1AppsByAppIDEnvVars"},
        {"context": "apps", "go": "AppsPostApiV1AppsByAppIDEnvVars"},
        {"context": "apps", "go": "AppsPutApiV1AppsByAppIDEnvVarsByKeyStagingValue"},
        {"context": "deployments", "go": "DeployDeleteApiV1AppsByAppIDGitConnection"},
        {"context": "deployments", "go": "DeployGetApiV1AppsByAppIDGitConnection"},
        {"context": "deployments", "go": "DeployPatchApiV1AppsByAppIDGitConnection"},
        {"context": "deployments", "go": "DeployPostApiV1AppsByAppIDGitConnection"},
        {"context": "deployments", "go": "DeployPostApiV1AppsByAppIDGitGithubConnect"},
        {"context": "deployments", "go": "DeployGetApiV1AppsByAppIDGitGithubInstallStart"},
        {"context": "apps", "go": "AppsDeleteApiV1AppsByAppIDLikes"},
        {"context": "apps", "go": "AppsPostApiV1AppsByAppIDLikes"},
        {"context": "apps", "go": "AppsGetApiV1AppsByAppIDLikesMe"},
        {"context": "deployments", "go": "DeployGetApiV1AppsByAppIDLogs"},
        {"context": "identity", "go": "AuthPostApiV1AppsByAppIDOauthClients"},
        {"context": "deployments", "go": "DeployPostApiV1AppsByAppIDPromotionsByRequestIDRetry"},
        {"context": "apps", "go": "AppsDeleteApiV1AppsByAppIDRawDb"},
        {"context": "apps", "go": "AppsPostApiV1AppsByAppIDRawDb"},
        {"context": "deployments", "go": "DeployGetApiV1AppsByAppIDReleases"},
        {"context": "deployments", "go": "DeployGetApiV1AppsByAppIDReleasesPromotePreflight"},
        {"context": "deployments", "go": "DeployDeleteApiV1AppsByAppIDStaging"},
        {"context": "deployments", "go": "DeployPutApiV1AppsByAppIDStaging"},
        {"context": "apps", "go": "AppsGetApiV1AppsDiscover"},
        {"context": "apps", "go": "AppsGetApiV1AppsSearch"},
        {"context": "apps", "go": "AppsDeleteApiV1CommentsByCommentID"},
        {"context": "deployments", "go": "DeployPostApiV1GitGithubComplete"},
        {"context": "deployments", "go": "DeployGetApiV1GithubAccounts"},
        {"context": "deployments", "go": "DeployGetApiV1GithubInstallationsByInstallationIDRepositories"},
        {"context": "identity", "go": "AuthGetApiV1Me"},
        {"context": "apps", "go": "AppsGetApiV1MeAppsOwned"},
        {"context": "apps", "go": "AppsGetApiV1MeAppsReceived"},
        {"context": "apps", "go": "AppsGetApiV1MeAppsWorkspace"},
        {"context": "notifications", "go": "NotificationsGetApiV1MeNotifications"},
        {"context": "notifications", "go": "NotificationsPostApiV1MeNotificationsByNotificationIDRead"},
        {"context": "notifications", "go": "NotificationsPostApiV1MeNotificationsReadAll"},
        {"context": "data", "go": "SchemaGetApiV1MePersonalAccessTokens"},
        {"context": "data", "go": "SchemaPostApiV1MePersonalAccessTokens"},
        {"context": "data", "go": "SchemaDeleteApiV1MePersonalAccessTokensByPatID"},
        {"context": "identity", "go": "AuthGetApiV1OauthClientsByClientID"},
        {"context": "identity", "go": "AuthDeleteApiV1OauthClientsByClientIDGrantsMe"},
        {"context": "apps", "go": "AppsGetApiV1Templates"},
        {"context": "tenants", "go": "TenantsGetApiV1Tenants"},
        {"context": "tenants", "go": "TenantsGetApiV1TenantsByTenantID"},
        {"context": "deployments", "go": "DeployPostApiV1TenantsByTenantIDAppBootstraps"},
        {"context": "deployments", "go": "DeployGetApiV1TenantsByTenantIDAppBootstrapsByBootstrapID"},
        {"context": "apps", "go": "AppsGetApiV1TenantsByTenantIDApps"},
        {"context": "apps", "go": "AppsPostApiV1TenantsByTenantIDApps"},
        {"context": "apps", "go": "AppsGetApiV1TenantsByTenantIDAppsCheckAvailability"},
        {"context": "gateway", "go": "GatewayGetApiV1TenantsByTenantIDConnectors"},
        {"context": "gateway", "go": "GatewayGetApiV1TenantsByTenantIDConnectorsByConnectorID"},
        {"context": "gateway", "go": "GatewayPostApiV1TenantsByTenantIDConnectorsByConnectorIDDiscover"},
        {"context": "gateway", "go": "GatewayGetApiV1TenantsByTenantIDConnectorsByConnectorIDResources"},
        {"context": "deployments", "go": "DeployGetApiV1TenantsByTenantIDDeployments"},
        {"context": "apps", "go": "AppsGetApiV1TenantsByTenantIDDiscoverApps"},
        {"context": "gateway", "go": "GatewayPostApiV1TenantsByTenantIDGatewayDocumentInvoke"},
        {"context": "gateway", "go": "GatewayPostApiV1TenantsByTenantIDGatewayFileInvoke"},
        {"context": "gateway", "go": "GatewayPostApiV1TenantsByTenantIDGatewayInvoke"},
        {"context": "gateway", "go": "GatewayPostApiV1TenantsByTenantIDGatewayQuery"},
        {"context": "gateway", "go": "GatewayPostApiV1TenantsByTenantIDGatewaySessions"},
        {"context": "gateway", "go": "GatewayDeleteApiV1TenantsByTenantIDGatewaySessionsBySessionID"},
        {"context": "gateway", "go": "GatewayGetApiV1TenantsByTenantIDMeConnectors"},
        {"context": "gateway", "go": "GatewayGetApiV1TenantsByTenantIDMeConnectorsByConnectorIDResources"},
        {"context": "authz", "go": "AuthorizationGetApiV1TenantsByTenantIDMeGrants"},
        {"context": "tenants", "go": "TenantsGetApiV1TenantsByTenantIDMembersDirectory"},
        {"context": "tenants", "go": "TenantsGetApiV1TenantsByTenantIDOrgDirectory"},
        {"context": "apps", "go": "AppsGetApiV1UsersMeApps"},
        {"context": "identity", "go": "AuthPostAuthLogout"},
        {"context": "identity", "go": "AuthPostAuthRefresh"},
        {"context": "gateway", "go": "ConfigGetConfigPublic"},
        {"context": "gateway", "go": "GatewayGetOauthGoogleCallback"},
        {"context": "identity", "go": "AuthGetOauthUserinfo"},
    }
    if len(expected) != len(Routes) { t.Fatalf("expected metadata drift %d routes %d", len(expected), len(Routes)) }
    for _, item := range expected {
        typ := contexts[item["context"]]
        if typ == nil { t.Fatalf("missing context %s", item["context"]) }
        if _, ok := typ.MethodByName(item["go"]); !ok { t.Fatalf("missing generated method %s on %s", item["go"], item["context"]) }
    }
}
