package axhub

import (
    "reflect"
    "testing"
)

func TestGeneratedOperationFacadesCoverAllRoutes(t *testing.T) {
    c := NewClient(Config{})
    contexts := map[string]reflect.Type{
        "apps": reflect.TypeOf(c.Apps),
        "identity": reflect.TypeOf(c.Identity()),
        "tenants": reflect.TypeOf(c.Tenants()),
        "authz": reflect.TypeOf(c.Authz()),
        "audit": reflect.TypeOf(c.Audit()),
        "gateway": reflect.TypeOf(c.Gateway()),
        "cost": reflect.TypeOf(c.Cost()),
        "data": reflect.TypeOf(c.Data()),
        "deployments": reflect.TypeOf(c.Deployments()),
    }
    expected := []map[string]string{
        {"context": "identity", "go": "AuthGetWellKnownJwksJson"},
        {"context": "identity", "go": "AuthGetWellKnownOauthAuthorizationServer"},
        {"context": "identity", "go": "AuthGetWellKnownOpenidConfiguration"},
        {"context": "apps", "go": "AppsGetApiV1AdminTemplates"},
        {"context": "apps", "go": "AppsPostApiV1AdminTemplates"},
        {"context": "apps", "go": "AppsGetApiV1AdminTemplatesByTemplateID"},
        {"context": "apps", "go": "AppsPatchApiV1AdminTemplatesByTemplateID"},
        {"context": "identity", "go": "AuthPostApiV1AdminUsersByUidRevokeAll"},
        {"context": "apps", "go": "AppsDeleteApiV1AppsByAppID"},
        {"context": "apps", "go": "AppsGetApiV1AppsByAppID"},
        {"context": "apps", "go": "AppsPatchApiV1AppsByAppID"},
        {"context": "apps", "go": "AppsDeleteApiV1AppsByAppIDAccess"},
        {"context": "apps", "go": "AppsPostApiV1AppsByAppIDAccess"},
        {"context": "apps", "go": "AppsGetApiV1AppsByAppIDAccessMe"},
        {"context": "apps", "go": "AppsPostApiV1AppsByAppIDArchive"},
        {"context": "apps", "go": "AppsGetApiV1AppsByAppIDComments"},
        {"context": "apps", "go": "AppsPostApiV1AppsByAppIDComments"},
        {"context": "data", "go": "SchemaGetApiV1AppsByAppIDDbTables"},
        {"context": "data", "go": "SchemaGetApiV1AppsByAppIDDbTablesByTableRows"},
        {"context": "deployments", "go": "DeployGetApiV1AppsByAppIDDeployments"},
        {"context": "deployments", "go": "DeployPostApiV1AppsByAppIDDeployments"},
        {"context": "deployments", "go": "DeployGetApiV1AppsByAppIDDeploymentsByDid"},
        {"context": "deployments", "go": "DeployPostApiV1AppsByAppIDDeploymentsByDidCancel"},
        {"context": "deployments", "go": "DeployPostApiV1AppsByAppIDDeploymentsByDidRollback"},
        {"context": "deployments", "go": "DeployGetApiV1AppsByAppIDDiagnosis"},
        {"context": "apps", "go": "AppsGetApiV1AppsByAppIDEnvVars"},
        {"context": "apps", "go": "AppsPostApiV1AppsByAppIDEnvVars"},
        {"context": "apps", "go": "AppsDeleteApiV1AppsByAppIDEnvVarsByKey"},
        {"context": "apps", "go": "AppsPutApiV1AppsByAppIDEnvVarsByKeyStagingValue"},
        {"context": "deployments", "go": "DeployDeleteApiV1AppsByAppIDGitConnection"},
        {"context": "deployments", "go": "DeployGetApiV1AppsByAppIDGitConnection"},
        {"context": "deployments", "go": "DeployPatchApiV1AppsByAppIDGitConnection"},
        {"context": "deployments", "go": "DeployPostApiV1AppsByAppIDGitConnection"},
        {"context": "deployments", "go": "DeployPostApiV1AppsByAppIDGitGithubConnect"},
        {"context": "deployments", "go": "DeployGetApiV1AppsByAppIDGitGithubInstallStart"},
        {"context": "apps", "go": "AppsPostApiV1AppsByAppIDIconDarkUploadUrl"},
        {"context": "apps", "go": "AppsPostApiV1AppsByAppIDIconUploadUrl"},
        {"context": "apps", "go": "AppsPostApiV1AppsByAppIDInvitations"},
        {"context": "apps", "go": "AppsDeleteApiV1AppsByAppIDInvitationsByUserID"},
        {"context": "apps", "go": "AppsDeleteApiV1AppsByAppIDLikes"},
        {"context": "apps", "go": "AppsPostApiV1AppsByAppIDLikes"},
        {"context": "apps", "go": "AppsGetApiV1AppsByAppIDLikesMe"},
        {"context": "deployments", "go": "DeployGetApiV1AppsByAppIDLogs"},
        {"context": "apps", "go": "AppsGetApiV1AppsByAppIDMembers"},
        {"context": "identity", "go": "AuthPostApiV1AppsByAppIDOauthClients"},
        {"context": "apps", "go": "AppsDeleteApiV1AppsByAppIDPermanent"},
        {"context": "deployments", "go": "DeployPostApiV1AppsByAppIDPromotionsByRequestIDRetry"},
        {"context": "apps", "go": "AppsDeleteApiV1AppsByAppIDRawDb"},
        {"context": "apps", "go": "AppsPostApiV1AppsByAppIDRawDb"},
        {"context": "apps", "go": "AppsPostApiV1AppsByAppIDReactivate"},
        {"context": "deployments", "go": "DeployGetApiV1AppsByAppIDReleases"},
        {"context": "deployments", "go": "DeployGetApiV1AppsByAppIDReleasesPromotePreflight"},
        {"context": "apps", "go": "AppsPostApiV1AppsByAppIDResume"},
        {"context": "apps", "go": "AppsGetApiV1AppsByAppIDReviewRequests"},
        {"context": "apps", "go": "AppsPostApiV1AppsByAppIDReviewRequests"},
        {"context": "deployments", "go": "DeployDeleteApiV1AppsByAppIDStaging"},
        {"context": "deployments", "go": "DeployPutApiV1AppsByAppIDStaging"},
        {"context": "apps", "go": "AppsPostApiV1AppsByAppIDSuspend"},
        {"context": "apps", "go": "AppsGetApiV1AppsDiscover"},
        {"context": "apps", "go": "AppsGetApiV1AppsSearch"},
        {"context": "apps", "go": "AppsDeleteApiV1CommentsByCommentID"},
        {"context": "deployments", "go": "DeployPostApiV1GitGithubComplete"},
        {"context": "deployments", "go": "DeployGetApiV1GithubAccounts"},
        {"context": "deployments", "go": "DeployGetApiV1GithubInstallationsByInstallationIDRepositories"},
        {"context": "tenants", "go": "TenantsGetApiV1InviteLinksByToken"},
        {"context": "tenants", "go": "TenantsPostApiV1InviteLinksByTokenAccept"},
        {"context": "identity", "go": "AuthGetApiV1Me"},
        {"context": "apps", "go": "AppsGetApiV1MeAppsOwned"},
        {"context": "apps", "go": "AppsGetApiV1MeAppsReceived"},
        {"context": "apps", "go": "AppsGetApiV1MeAppsWorkspace"},
        {"context": "identity", "go": "AuthPostApiV1MeInvitationsByInvitationIDAccept"},
        {"context": "data", "go": "SchemaGetApiV1MePersonalAccessTokens"},
        {"context": "data", "go": "SchemaPostApiV1MePersonalAccessTokens"},
        {"context": "data", "go": "SchemaDeleteApiV1MePersonalAccessTokensByPatID"},
        {"context": "identity", "go": "AuthGetApiV1OauthClientsByClientID"},
        {"context": "identity", "go": "AuthDeleteApiV1OauthClientsByClientIDGrantsMe"},
        {"context": "apps", "go": "AppsGetApiV1ResourcePresets"},
        {"context": "apps", "go": "AppsGetApiV1ReviewRequestsByRrID"},
        {"context": "apps", "go": "AppsPostApiV1ReviewRequestsByRrIDApprove"},
        {"context": "apps", "go": "AppsPostApiV1ReviewRequestsByRrIDReject"},
        {"context": "apps", "go": "AppsGetApiV1ReviewRequestsHistory"},
        {"context": "apps", "go": "AppsGetApiV1ReviewRequestsPending"},
        {"context": "apps", "go": "AppsGetApiV1StaticAuthStart"},
        {"context": "apps", "go": "AppsGetApiV1Templates"},
        {"context": "tenants", "go": "TenantsGetApiV1Tenants"},
        {"context": "tenants", "go": "TenantsPostApiV1Tenants"},
        {"context": "tenants", "go": "TenantsDeleteApiV1TenantsByTenantID"},
        {"context": "tenants", "go": "TenantsGetApiV1TenantsByTenantID"},
        {"context": "tenants", "go": "TenantsPatchApiV1TenantsByTenantID"},
        {"context": "deployments", "go": "DeployPostApiV1TenantsByTenantIDAppBootstraps"},
        {"context": "deployments", "go": "DeployGetApiV1TenantsByTenantIDAppBootstrapsByBootstrapID"},
        {"context": "apps", "go": "AppsGetApiV1TenantsByTenantIDApps"},
        {"context": "apps", "go": "AppsPostApiV1TenantsByTenantIDApps"},
        {"context": "apps", "go": "AppsGetApiV1TenantsByTenantIDAppsByAppIDStaticReleases"},
        {"context": "apps", "go": "AppsPostApiV1TenantsByTenantIDAppsByAppIDStaticReleases"},
        {"context": "apps", "go": "AppsDeleteApiV1TenantsByTenantIDAppsByAppIDStaticReleasesByReleaseID"},
        {"context": "apps", "go": "AppsPostApiV1TenantsByTenantIDAppsByAppIDStaticReleasesByReleaseIDActivate"},
        {"context": "apps", "go": "AppsPostApiV1TenantsByTenantIDAppsByAppIDStaticReleasesByReleaseIDFinalize"},
        {"context": "apps", "go": "AppsPostApiV1TenantsByTenantIDAppsByAppIDStaticReleasesByReleaseIDPromoteApprove"},
        {"context": "apps", "go": "AppsPostApiV1TenantsByTenantIDAppsByAppIDStaticReleasesByReleaseIDPromoteReject"},
        {"context": "apps", "go": "AppsPostApiV1TenantsByTenantIDAppsByAppIDStaticReleasesByReleaseIDPromoteRequest"},
        {"context": "apps", "go": "AppsPostApiV1TenantsByTenantIDAppsByAppIDStaticReleasesByReleaseIDRollback"},
        {"context": "apps", "go": "AppsPostApiV1TenantsByTenantIDAppsByAppIDStaticReleasesByReleaseIDStage"},
        {"context": "apps", "go": "AppsGetApiV1TenantsByTenantIDAppsByAppIDStaticSite"},
        {"context": "apps", "go": "AppsPatchApiV1TenantsByTenantIDAppsByAppIDStaticSite"},
        {"context": "apps", "go": "AppsPostApiV1TenantsByTenantIDAppsByAppIDStaticSiteStagingDisable"},
        {"context": "apps", "go": "AppsPostApiV1TenantsByTenantIDAppsByAppIDStaticSiteStagingEnable"},
        {"context": "apps", "go": "AppsPostApiV1TenantsByTenantIDAppsByAppIDStaticSiteUnpublish"},
        {"context": "apps", "go": "AppsGetApiV1TenantsByTenantIDAppsCheckAvailability"},
        {"context": "apps", "go": "AppsPostApiV1TenantsByTenantIDAppsIconUploadUrl"},
        {"context": "audit", "go": "AuditGetApiV1TenantsByTenantIDAuditEvents"},
        {"context": "audit", "go": "AuditGetApiV1TenantsByTenantIDAuditEventsByEventID"},
        {"context": "audit", "go": "AuditPostApiV1TenantsByTenantIDAuditEventsAnonymize"},
        {"context": "audit", "go": "AuditGetApiV1TenantsByTenantIDAuditEventsIntegrityCheck"},
        {"context": "apps", "go": "AppsGetApiV1TenantsByTenantIDCategories"},
        {"context": "apps", "go": "AppsPostApiV1TenantsByTenantIDCategories"},
        {"context": "apps", "go": "AppsDeleteApiV1TenantsByTenantIDCategoriesByCategoryID"},
        {"context": "apps", "go": "AppsGetApiV1TenantsByTenantIDCategoriesByCategoryID"},
        {"context": "apps", "go": "AppsPatchApiV1TenantsByTenantIDCategoriesByCategoryID"},
        {"context": "gateway", "go": "GatewayGetApiV1TenantsByTenantIDConnectors"},
        {"context": "gateway", "go": "GatewayPostApiV1TenantsByTenantIDConnectors"},
        {"context": "gateway", "go": "GatewayDeleteApiV1TenantsByTenantIDConnectorsByConnectorID"},
        {"context": "gateway", "go": "GatewayGetApiV1TenantsByTenantIDConnectorsByConnectorID"},
        {"context": "gateway", "go": "GatewayPatchApiV1TenantsByTenantIDConnectorsByConnectorID"},
        {"context": "gateway", "go": "GatewayPostApiV1TenantsByTenantIDConnectorsByConnectorIDDiscover"},
        {"context": "gateway", "go": "GatewayGetApiV1TenantsByTenantIDConnectorsByConnectorIDResources"},
        {"context": "gateway", "go": "GatewayPostApiV1TenantsByTenantIDConnectorsByConnectorIDTestConnection"},
        {"context": "gateway", "go": "GatewayPostApiV1TenantsByTenantIDConnectorsOauthGoogleFinalize"},
        {"context": "gateway", "go": "GatewayPostApiV1TenantsByTenantIDConnectorsOauthGoogleStart"},
        {"context": "cost", "go": "CostGetApiV1TenantsByTenantIDCostByApp"},
        {"context": "cost", "go": "CostGetApiV1TenantsByTenantIDCostByCostCenter"},
        {"context": "cost", "go": "CostGetApiV1TenantsByTenantIDCostExport"},
        {"context": "cost", "go": "CostGetApiV1TenantsByTenantIDCostMonths"},
        {"context": "cost", "go": "CostGetApiV1TenantsByTenantIDCostSummary"},
        {"context": "cost", "go": "CostGetApiV1TenantsByTenantIDCostTimeseries"},
        {"context": "deployments", "go": "DeployGetApiV1TenantsByTenantIDDeployments"},
        {"context": "apps", "go": "AppsGetApiV1TenantsByTenantIDDiscoverApps"},
        {"context": "tenants", "go": "TenantsGetApiV1TenantsByTenantIDEmailDomains"},
        {"context": "tenants", "go": "TenantsPostApiV1TenantsByTenantIDEmailDomains"},
        {"context": "tenants", "go": "TenantsDeleteApiV1TenantsByTenantIDEmailDomainsByDomain"},
        {"context": "gateway", "go": "GatewayPostApiV1TenantsByTenantIDGatewayDocumentInvoke"},
        {"context": "gateway", "go": "GatewayPostApiV1TenantsByTenantIDGatewayFileInvoke"},
        {"context": "gateway", "go": "GatewayPostApiV1TenantsByTenantIDGatewayInvoke"},
        {"context": "gateway", "go": "GatewayPostApiV1TenantsByTenantIDGatewayQuery"},
        {"context": "gateway", "go": "GatewayPostApiV1TenantsByTenantIDGatewaySessions"},
        {"context": "gateway", "go": "GatewayDeleteApiV1TenantsByTenantIDGatewaySessionsBySessionID"},
        {"context": "authz", "go": "AuthorizationGetApiV1TenantsByTenantIDGrants"},
        {"context": "authz", "go": "AuthorizationPostApiV1TenantsByTenantIDGrants"},
        {"context": "authz", "go": "AuthorizationDeleteApiV1TenantsByTenantIDGrantsByGrantID"},
        {"context": "authz", "go": "AuthorizationGetApiV1TenantsByTenantIDGrantsByGrantID"},
        {"context": "tenants", "go": "TenantsGetApiV1TenantsByTenantIDGroups"},
        {"context": "tenants", "go": "TenantsPostApiV1TenantsByTenantIDGroups"},
        {"context": "tenants", "go": "TenantsDeleteApiV1TenantsByTenantIDGroupsByGroupID"},
        {"context": "tenants", "go": "TenantsPatchApiV1TenantsByTenantIDGroupsByGroupID"},
        {"context": "tenants", "go": "TenantsDeleteApiV1TenantsByTenantIDIcon"},
        {"context": "tenants", "go": "TenantsPostApiV1TenantsByTenantIDIconUploadUrl"},
        {"context": "identity", "go": "AuthGetApiV1TenantsByTenantIDIdentityProviders"},
        {"context": "identity", "go": "AuthPostApiV1TenantsByTenantIDIdentityProviders"},
        {"context": "identity", "go": "AuthPostApiV1TenantsByTenantIDIdentityProvidersByProviderIDDisable"},
        {"context": "identity", "go": "AuthPostApiV1TenantsByTenantIDIdentityProvidersByProviderIDEnable"},
        {"context": "cost", "go": "CostGetApiV1TenantsByTenantIDInfraAppsByAppIDUsageSeries"},
        {"context": "cost", "go": "CostGetApiV1TenantsByTenantIDInfraUsage"},
        {"context": "tenants", "go": "TenantsGetApiV1TenantsByTenantIDInvitations"},
        {"context": "tenants", "go": "TenantsPostApiV1TenantsByTenantIDInvitations"},
        {"context": "tenants", "go": "TenantsDeleteApiV1TenantsByTenantIDInvitationsByInvitationID"},
        {"context": "tenants", "go": "TenantsPostApiV1TenantsByTenantIDInvitationsBulk"},
        {"context": "tenants", "go": "TenantsGetApiV1TenantsByTenantIDInviteLinks"},
        {"context": "tenants", "go": "TenantsPostApiV1TenantsByTenantIDInviteLinks"},
        {"context": "tenants", "go": "TenantsDeleteApiV1TenantsByTenantIDInviteLinksByLinkID"},
        {"context": "gateway", "go": "GatewayGetApiV1TenantsByTenantIDMeConnectors"},
        {"context": "gateway", "go": "GatewayGetApiV1TenantsByTenantIDMeConnectorsByConnectorIDResources"},
        {"context": "authz", "go": "AuthorizationGetApiV1TenantsByTenantIDMeGrants"},
        {"context": "tenants", "go": "TenantsGetApiV1TenantsByTenantIDMembers"},
        {"context": "tenants", "go": "TenantsPatchApiV1TenantsByTenantIDMembersByMembershipID"},
        {"context": "tenants", "go": "TenantsPostApiV1TenantsByTenantIDMembersByMembershipIDDeactivate"},
        {"context": "tenants", "go": "TenantsPatchApiV1TenantsByTenantIDMembersByMembershipIDGroup"},
        {"context": "tenants", "go": "TenantsPostApiV1TenantsByTenantIDMembersByMembershipIDReactivate"},
        {"context": "tenants", "go": "TenantsPostApiV1TenantsByTenantIDMembersByMembershipIDRestoreScim"},
        {"context": "tenants", "go": "TenantsDeleteApiV1TenantsByTenantIDMembersByUserIDSeat"},
        {"context": "tenants", "go": "TenantsPostApiV1TenantsByTenantIDMembersByUserIDSeat"},
        {"context": "tenants", "go": "TenantsGetApiV1TenantsByTenantIDMembersDirectory"},
        {"context": "authz", "go": "AuthorizationGetApiV1TenantsByTenantIDPresets"},
        {"context": "authz", "go": "AuthorizationPostApiV1TenantsByTenantIDPresets"},
        {"context": "authz", "go": "AuthorizationDeleteApiV1TenantsByTenantIDPresetsByPresetID"},
        {"context": "authz", "go": "AuthorizationGetApiV1TenantsByTenantIDPresetsByPresetID"},
        {"context": "authz", "go": "AuthorizationPatchApiV1TenantsByTenantIDPresetsByPresetID"},
        {"context": "tenants", "go": "TenantsGetApiV1TenantsByTenantIDScimConnection"},
        {"context": "tenants", "go": "TenantsDeleteApiV1TenantsByTenantIDScimToken"},
        {"context": "tenants", "go": "TenantsPostApiV1TenantsByTenantIDScimToken"},
        {"context": "authz", "go": "AuthorizationGetApiV1TenantsByTenantIDSubjects"},
        {"context": "authz", "go": "AuthorizationPostApiV1TenantsByTenantIDSubjects"},
        {"context": "authz", "go": "AuthorizationGetApiV1TenantsByTenantIDSubjectsBySubjectID"},
        {"context": "apps", "go": "AppsGetApiV1UsersMeApps"},
        {"context": "identity", "go": "AuthGetAuthByProviderIDStart"},
        {"context": "identity", "go": "IdentityGetAuthGithub"},
        {"context": "identity", "go": "IdentityGetAuthGithubCallback"},
        {"context": "identity", "go": "AuthGetAuthGoogleOauth2Callback"},
        {"context": "identity", "go": "AuthGetAuthGoogleOauth2Start"},
        {"context": "identity", "go": "AuthPostAuthLogout"},
        {"context": "identity", "go": "AuthGetAuthOidcCallback"},
        {"context": "identity", "go": "AuthGetAuthProviders"},
        {"context": "identity", "go": "AuthPostAuthRefresh"},
        {"context": "identity", "go": "AuthGetAuthSilentCallback"},
        {"context": "identity", "go": "AuthGetAuthSilentStart"},
        {"context": "gateway", "go": "ConfigGetConfigPublic"},
        {"context": "apps", "go": "AppsGetInternalAppAccess"},
        {"context": "identity", "go": "AuthGetOauthAuthorize"},
        {"context": "identity", "go": "AuthPostOauthAuthorizeTenant"},
        {"context": "identity", "go": "AuthPostOauthDeviceAuthorization"},
        {"context": "identity", "go": "AuthPostOauthDeviceAuthorize"},
        {"context": "identity", "go": "AuthGetOauthDeviceLookup"},
        {"context": "gateway", "go": "GatewayGetOauthGoogleCallback"},
        {"context": "identity", "go": "AuthPostOauthRegister"},
        {"context": "identity", "go": "AuthPostOauthRevoke"},
        {"context": "identity", "go": "AuthPostOauthToken"},
        {"context": "identity", "go": "AuthGetOauthUserinfo"},
        {"context": "deployments", "go": "DeployPostWebhooksGithub"},
    }
    if len(expected) != len(Routes) { t.Fatalf("expected metadata drift %d routes %d", len(expected), len(Routes)) }
    for _, item := range expected {
        typ := contexts[item["context"]]
        if typ == nil { t.Fatalf("missing context %s", item["context"]) }
        if _, ok := typ.MethodByName(item["go"]); !ok { t.Fatalf("missing generated method %s on %s", item["go"], item["context"]) }
    }
}
