package axhub

import (
    "reflect"
    "testing"
)

func TestGeneratedOperationFacadesCoverAllRoutes(t *testing.T) {
    c := NewClient(Config{})
    contexts := map[string]reflect.Type{
        "apps": reflect.TypeOf(c.Apps),
        "identity": reflect.TypeOf(c.Identity()),
        "tenants": reflect.TypeOf(c.Tenants()),
        "authz": reflect.TypeOf(c.Authz()),
        "audit": reflect.TypeOf(c.Audit()),
        "gateway": reflect.TypeOf(c.Gateway()),
        "data": reflect.TypeOf(c.Data()),
        "deployments": reflect.TypeOf(c.Deployments()),
    }
    expected := []map[string]string{
        {"context": "identity", "go": "AuthGetWellKnownJwksJson"},
        {"context": "identity", "go": "AuthGetWellKnownOpenidConfiguration"},
        {"context": "apps", "go": "AppsGetApiV1AdminTemplates"},
        {"context": "apps", "go": "AppsPostApiV1AdminTemplates"},
        {"context": "apps", "go": "AppsGetApiV1AdminTemplatesByTemplateID"},
        {"context": "apps", "go": "AppsPatchApiV1AdminTemplatesByTemplateID"},
        {"context": "identity", "go": "AuthPostApiV1AdminUsersByUidRevokeAll"},
        {"context": "apps", "go": "AppsDeleteApiV1AppsByAppID"},
        {"context": "apps", "go": "AppsGetApiV1AppsByAppID"},
        {"context": "apps", "go": "AppsPatchApiV1AppsByAppID"},
        {"context": "apps", "go": "AppsDeleteApiV1AppsByAppIDAccess"},
        {"context": "apps", "go": "AppsPostApiV1AppsByAppIDAccess"},
        {"context": "apps", "go": "AppsGetApiV1AppsByAppIDAccessMe"},
        {"context": "apps", "go": "AppsGetApiV1AppsByAppIDComments"},
        {"context": "apps", "go": "AppsPostApiV1AppsByAppIDComments"},
        {"context": "deployments", "go": "DeployGetApiV1AppsByAppIDDeployments"},
        {"context": "deployments", "go": "DeployPostApiV1AppsByAppIDDeployments"},
        {"context": "deployments", "go": "DeployGetApiV1AppsByAppIDDeploymentsByDid"},
        {"context": "deployments", "go": "DeployPostApiV1AppsByAppIDDeploymentsByDidCancel"},
        {"context": "deployments", "go": "DeployPostApiV1AppsByAppIDDeploymentsByDidRollback"},
        {"context": "apps", "go": "AppsGetApiV1AppsByAppIDEnvVars"},
        {"context": "apps", "go": "AppsPostApiV1AppsByAppIDEnvVars"},
        {"context": "apps", "go": "AppsDeleteApiV1AppsByAppIDEnvVarsByKey"},
        {"context": "deployments", "go": "DeployDeleteApiV1AppsByAppIDGitConnection"},
        {"context": "deployments", "go": "DeployGetApiV1AppsByAppIDGitConnection"},
        {"context": "deployments", "go": "DeployPatchApiV1AppsByAppIDGitConnection"},
        {"context": "deployments", "go": "DeployPostApiV1AppsByAppIDGitConnection"},
        {"context": "deployments", "go": "DeployGetApiV1AppsByAppIDGitGithubInstallStart"},
        {"context": "apps", "go": "AppsPostApiV1AppsByAppIDIconDarkUploadUrl"},
        {"context": "apps", "go": "AppsPostApiV1AppsByAppIDIconUploadUrl"},
        {"context": "apps", "go": "AppsPostApiV1AppsByAppIDInvitations"},
        {"context": "apps", "go": "AppsDeleteApiV1AppsByAppIDInvitationsByUserID"},
        {"context": "apps", "go": "AppsDeleteApiV1AppsByAppIDLikes"},
        {"context": "apps", "go": "AppsPostApiV1AppsByAppIDLikes"},
        {"context": "apps", "go": "AppsGetApiV1AppsByAppIDLikesMe"},
        {"context": "deployments", "go": "DeployGetApiV1AppsByAppIDLogs"},
        {"context": "apps", "go": "AppsGetApiV1AppsByAppIDMembers"},
        {"context": "identity", "go": "AuthPostApiV1AppsByAppIDOauthClients"},
        {"context": "apps", "go": "AppsDeleteApiV1AppsByAppIDPermanent"},
        {"context": "apps", "go": "AppsPostApiV1AppsByAppIDResume"},
        {"context": "apps", "go": "AppsGetApiV1AppsByAppIDReviewRequests"},
        {"context": "apps", "go": "AppsPostApiV1AppsByAppIDReviewRequests"},
        {"context": "apps", "go": "AppsPostApiV1AppsByAppIDSuspend"},
        {"context": "data", "go": "SchemaGetApiV1AppsByAppIDTables"},
        {"context": "data", "go": "SchemaPostApiV1AppsByAppIDTables"},
        {"context": "data", "go": "SchemaDeleteApiV1AppsByAppIDTablesByTableName"},
        {"context": "data", "go": "SchemaGetApiV1AppsByAppIDTablesByTableName"},
        {"context": "data", "go": "SchemaPostApiV1AppsByAppIDTablesByTableNameColumns"},
        {"context": "data", "go": "SchemaDeleteApiV1AppsByAppIDTablesByTableNameColumnsByColumnName"},
        {"context": "data", "go": "SchemaGetApiV1AppsByAppIDTablesByTableNameGrants"},
        {"context": "data", "go": "SchemaPostApiV1AppsByAppIDTablesByTableNameGrants"},
        {"context": "data", "go": "SchemaDeleteApiV1AppsByAppIDTablesByTableNameGrantsByGrantID"},
        {"context": "data", "go": "SchemaGetApiV1AppsByAppIDTablesByTableNameRows"},
        {"context": "data", "go": "SchemaGetApiV1AppsByAppIDTablesCheckAvailability"},
        {"context": "data", "go": "SchemaGetApiV1AppsByAppIDTablesColumnTypes"},
        {"context": "apps", "go": "AppsGetApiV1AppsDiscover"},
        {"context": "apps", "go": "AppsGetApiV1AppsSearch"},
        {"context": "gateway", "go": "GatewayGetApiV1CatalogKinds"},
        {"context": "apps", "go": "AppsDeleteApiV1CommentsByCommentID"},
        {"context": "gateway", "go": "GatewayGetApiV1Engines"},
        {"context": "deployments", "go": "DeployGetApiV1GithubAccounts"},
        {"context": "deployments", "go": "DeployGetApiV1GithubInstallationsByInstallationIDRepositories"},
        {"context": "identity", "go": "AuthGetApiV1Me"},
        {"context": "apps", "go": "AppsGetApiV1MeAppsOwned"},
        {"context": "apps", "go": "AppsGetApiV1MeAppsReceived"},
        {"context": "apps", "go": "AppsGetApiV1MeAppsWorkspace"},
        {"context": "data", "go": "SchemaGetApiV1MePersonalAccessTokens"},
        {"context": "data", "go": "SchemaPostApiV1MePersonalAccessTokens"},
        {"context": "data", "go": "SchemaDeleteApiV1MePersonalAccessTokensByPatID"},
        {"context": "identity", "go": "AuthGetApiV1OauthClientsByClientID"},
        {"context": "identity", "go": "AuthDeleteApiV1OauthClientsByClientIDGrantsMe"},
        {"context": "apps", "go": "AppsGetApiV1ReviewRequestsByRrID"},
        {"context": "apps", "go": "AppsPostApiV1ReviewRequestsByRrIDApprove"},
        {"context": "apps", "go": "AppsPostApiV1ReviewRequestsByRrIDReject"},
        {"context": "apps", "go": "AppsGetApiV1ReviewRequestsHistory"},
        {"context": "apps", "go": "AppsGetApiV1ReviewRequestsPending"},
        {"context": "apps", "go": "AppsGetApiV1Templates"},
        {"context": "tenants", "go": "TenantsGetApiV1Tenants"},
        {"context": "tenants", "go": "TenantsPostApiV1Tenants"},
        {"context": "tenants", "go": "TenantsDeleteApiV1TenantsByTenantID"},
        {"context": "tenants", "go": "TenantsGetApiV1TenantsByTenantID"},
        {"context": "tenants", "go": "TenantsPatchApiV1TenantsByTenantID"},
        {"context": "deployments", "go": "DeployPostApiV1TenantsByTenantIDAppBootstraps"},
        {"context": "deployments", "go": "DeployGetApiV1TenantsByTenantIDAppBootstrapsByBootstrapID"},
        {"context": "apps", "go": "AppsGetApiV1TenantsByTenantIDApps"},
        {"context": "apps", "go": "AppsPostApiV1TenantsByTenantIDApps"},
        {"context": "apps", "go": "AppsGetApiV1TenantsByTenantIDAppsCheckAvailability"},
        {"context": "apps", "go": "AppsPostApiV1TenantsByTenantIDAppsIconUploadUrl"},
        {"context": "audit", "go": "AuditGetApiV1TenantsByTenantIDAuditEvents"},
        {"context": "audit", "go": "AuditGetApiV1TenantsByTenantIDAuditEventsByEventID"},
        {"context": "audit", "go": "AuditPostApiV1TenantsByTenantIDAuditEventsAnonymize"},
        {"context": "audit", "go": "AuditGetApiV1TenantsByTenantIDAuditEventsIntegrityCheck"},
        {"context": "gateway", "go": "GatewayGetApiV1TenantsByTenantIDCatalogConnectors"},
        {"context": "gateway", "go": "GatewayGetApiV1TenantsByTenantIDCatalogResources"},
        {"context": "gateway", "go": "GatewayGetApiV1TenantsByTenantIDCatalogResourcesByConnectorByPath"},
        {"context": "gateway", "go": "GatewayPostApiV1TenantsByTenantIDCatalogResourcesByConnectorByPath"},
        {"context": "apps", "go": "AppsGetApiV1TenantsByTenantIDCategories"},
        {"context": "apps", "go": "AppsPostApiV1TenantsByTenantIDCategories"},
        {"context": "apps", "go": "AppsDeleteApiV1TenantsByTenantIDCategoriesByCategoryID"},
        {"context": "apps", "go": "AppsGetApiV1TenantsByTenantIDCategoriesByCategoryID"},
        {"context": "apps", "go": "AppsPatchApiV1TenantsByTenantIDCategoriesByCategoryID"},
        {"context": "gateway", "go": "GatewayGetApiV1TenantsByTenantIDConnectors"},
        {"context": "gateway", "go": "GatewayPostApiV1TenantsByTenantIDConnectors"},
        {"context": "gateway", "go": "GatewayDeleteApiV1TenantsByTenantIDConnectorsByConnectorID"},
        {"context": "gateway", "go": "GatewayPatchApiV1TenantsByTenantIDConnectorsByConnectorID"},
        {"context": "gateway", "go": "GatewayPostApiV1TenantsByTenantIDConnectorsByConnectorIDCredentials"},
        {"context": "gateway", "go": "GatewayGetApiV1TenantsByTenantIDConnectorsByConnectorIDDiscover"},
        {"context": "apps", "go": "AppsGetApiV1TenantsByTenantIDDiscoverApps"},
        {"context": "gateway", "go": "GatewayPostApiV1TenantsByTenantIDGatewayQuery"},
        {"context": "authz", "go": "AuthorizationGetApiV1TenantsByTenantIDGrants"},
        {"context": "authz", "go": "AuthorizationPostApiV1TenantsByTenantIDGrantsByGrantIDGrant"},
        {"context": "authz", "go": "AuthorizationPostApiV1TenantsByTenantIDGrantsByGrantIDRevoke"},
        {"context": "tenants", "go": "TenantsDeleteApiV1TenantsByTenantIDIcon"},
        {"context": "tenants", "go": "TenantsPostApiV1TenantsByTenantIDIconUploadUrl"},
        {"context": "identity", "go": "AuthGetApiV1TenantsByTenantIDIdentityProviders"},
        {"context": "identity", "go": "AuthPostApiV1TenantsByTenantIDIdentityProviders"},
        {"context": "identity", "go": "AuthPostApiV1TenantsByTenantIDIdentityProvidersByProviderIDDisable"},
        {"context": "identity", "go": "AuthPostApiV1TenantsByTenantIDIdentityProvidersByProviderIDEnable"},
        {"context": "tenants", "go": "TenantsGetApiV1TenantsByTenantIDInvitations"},
        {"context": "tenants", "go": "TenantsPostApiV1TenantsByTenantIDInvitations"},
        {"context": "tenants", "go": "TenantsDeleteApiV1TenantsByTenantIDInvitationsByInvitationID"},
        {"context": "tenants", "go": "TenantsPostApiV1TenantsByTenantIDInvitationsBulk"},
        {"context": "tenants", "go": "TenantsGetApiV1TenantsByTenantIDMembers"},
        {"context": "tenants", "go": "TenantsPatchApiV1TenantsByTenantIDMembersByMembershipID"},
        {"context": "tenants", "go": "TenantsPostApiV1TenantsByTenantIDMembersByMembershipIDDeactivate"},
        {"context": "tenants", "go": "TenantsPostApiV1TenantsByTenantIDMembersByMembershipIDReactivate"},
        {"context": "gateway", "go": "GatewayGetApiV1TenantsByTenantIDResources"},
        {"context": "gateway", "go": "GatewayDeleteApiV1TenantsByTenantIDResourcesByResourceID"},
        {"context": "gateway", "go": "GatewayPatchApiV1TenantsByTenantIDResourcesByResourceID"},
        {"context": "gateway", "go": "GatewayPostApiV1TenantsByTenantIDResourcesByResourceIDMove"},
        {"context": "gateway", "go": "GatewayPostApiV1TenantsByTenantIDResourcesByResourceIDTags"},
        {"context": "gateway", "go": "GatewayDeleteApiV1TenantsByTenantIDResourcesByResourceIDTagsByTagID"},
        {"context": "gateway", "go": "GatewayPostApiV1TenantsByTenantIDResourcesBulk"},
        {"context": "gateway", "go": "GatewayPostApiV1TenantsByTenantIDResourcesNamespaces"},
        {"context": "authz", "go": "AuthorizationGetApiV1TenantsByTenantIDSubjects"},
        {"context": "authz", "go": "AuthorizationPostApiV1TenantsByTenantIDSubjects"},
        {"context": "authz", "go": "AuthorizationDeleteApiV1TenantsByTenantIDSubjectsBySubjectID"},
        {"context": "authz", "go": "AuthorizationPatchApiV1TenantsByTenantIDSubjectsBySubjectID"},
        {"context": "authz", "go": "AuthorizationPostApiV1TenantsByTenantIDSubjectsBySubjectIDMove"},
        {"context": "authz", "go": "AuthorizationPostApiV1TenantsByTenantIDSubjectsBySubjectIDTags"},
        {"context": "authz", "go": "AuthorizationDeleteApiV1TenantsByTenantIDSubjectsBySubjectIDTagsByTagID"},
        {"context": "authz", "go": "AuthorizationGetApiV1TenantsByTenantIDTags"},
        {"context": "authz", "go": "AuthorizationPostApiV1TenantsByTenantIDTags"},
        {"context": "authz", "go": "AuthorizationDeleteApiV1TenantsByTenantIDTagsByTagID"},
        {"context": "authz", "go": "AuthorizationPatchApiV1TenantsByTenantIDTagsByTagID"},
        {"context": "apps", "go": "AppsGetApiV1UsersMeApps"},
        {"context": "identity", "go": "AuthGetAuthByProviderIDStart"},
        {"context": "identity", "go": "IdentityGetAuthGithub"},
        {"context": "identity", "go": "IdentityGetAuthGithubCallback"},
        {"context": "identity", "go": "AuthGetAuthGoogleOauth2Callback"},
        {"context": "identity", "go": "AuthGetAuthGoogleOauth2Start"},
        {"context": "identity", "go": "AuthPostAuthLogout"},
        {"context": "identity", "go": "AuthGetAuthOidcCallback"},
        {"context": "identity", "go": "AuthGetAuthProviders"},
        {"context": "identity", "go": "AuthPostAuthRefresh"},
        {"context": "identity", "go": "AuthGetAuthSilentCallback"},
        {"context": "identity", "go": "AuthGetAuthSilentStart"},
        {"context": "gateway", "go": "ConfigGetConfigPublic"},
        {"context": "data", "go": "SchemaGetDataByTenantSlugByAppSlugByTable"},
        {"context": "data", "go": "SchemaPostDataByTenantSlugByAppSlugByTable"},
        {"context": "data", "go": "SchemaGetDataByTenantSlugByAppSlugByTableCount"},
        {"context": "data", "go": "SchemaDeleteDataByTenantSlugByAppSlugByTableById"},
        {"context": "data", "go": "SchemaGetDataByTenantSlugByAppSlugByTableById"},
        {"context": "data", "go": "SchemaPatchDataByTenantSlugByAppSlugByTableById"},
        {"context": "apps", "go": "AppsGetInternalAppAccess"},
        {"context": "identity", "go": "AuthGetOauthAuthorize"},
        {"context": "identity", "go": "AuthPostOauthDeviceAuthorization"},
        {"context": "identity", "go": "AuthPostOauthDeviceAuthorize"},
        {"context": "identity", "go": "AuthGetOauthDeviceLookup"},
        {"context": "identity", "go": "AuthPostOauthRegister"},
        {"context": "identity", "go": "AuthPostOauthRevoke"},
        {"context": "identity", "go": "AuthPostOauthToken"},
        {"context": "identity", "go": "AuthGetOauthUserinfo"},
        {"context": "tenants", "go": "TenantsGetTenantsByTenantIDEmailDomains"},
        {"context": "tenants", "go": "TenantsPostTenantsByTenantIDEmailDomains"},
        {"context": "tenants", "go": "TenantsDeleteTenantsByTenantIDEmailDomainsByDomain"},
        {"context": "deployments", "go": "DeployPostWebhooksGithub"},
    }
    if len(expected) != len(Routes) { t.Fatalf("expected metadata drift %d routes %d", len(expected), len(Routes)) }
    for _, item := range expected {
        typ := contexts[item["context"]]
        if typ == nil { t.Fatalf("missing context %s", item["context"]) }
        if _, ok := typ.MethodByName(item["go"]); !ok { t.Fatalf("missing generated method %s on %s", item["go"], item["context"]) }
    }
}
