package axhub

type Route struct{ Method, Path, Tag, OperationID string }

var Routes = []Route{
	{Method: "GET", Path: "/.well-known/jwks.json", Tag: "Auth", OperationID: "authGetWellKnownJwksJson"},
	{Method: "GET", Path: "/.well-known/oauth-authorization-server", Tag: "Auth", OperationID: "authGetWellKnownOauthAuthorizationServer"},
	{Method: "GET", Path: "/.well-known/openid-configuration", Tag: "Auth", OperationID: "authGetWellKnownOpenidConfiguration"},
	{Method: "DELETE", Path: "/api/v1/apps/{appID}", Tag: "Apps", OperationID: "appsDeleteApiV1AppsByAppID"},
	{Method: "GET", Path: "/api/v1/apps/{appID}", Tag: "Apps", OperationID: "appsGetApiV1AppsByAppID"},
	{Method: "PATCH", Path: "/api/v1/apps/{appID}", Tag: "Apps", OperationID: "appsPatchApiV1AppsByAppID"},
	{Method: "DELETE", Path: "/api/v1/apps/{appID}/access", Tag: "Apps", OperationID: "appsDeleteApiV1AppsByAppIDAccess"},
	{Method: "POST", Path: "/api/v1/apps/{appID}/access", Tag: "Apps", OperationID: "appsPostApiV1AppsByAppIDAccess"},
	{Method: "GET", Path: "/api/v1/apps/{appID}/access/me", Tag: "Apps", OperationID: "appsGetApiV1AppsByAppIDAccessMe"},
	{Method: "POST", Path: "/api/v1/apps/{appID}/archive", Tag: "Apps", OperationID: "appsPostApiV1AppsByAppIDArchive"},
	{Method: "GET", Path: "/api/v1/apps/{appID}/comments", Tag: "Apps", OperationID: "appsGetApiV1AppsByAppIDComments"},
	{Method: "POST", Path: "/api/v1/apps/{appID}/comments", Tag: "Apps", OperationID: "appsPostApiV1AppsByAppIDComments"},
	{Method: "GET", Path: "/api/v1/apps/{appID}/db/tables", Tag: "Schema", OperationID: "schemaGetApiV1AppsByAppIDDbTables"},
	{Method: "GET", Path: "/api/v1/apps/{appID}/db/tables/{table}/rows", Tag: "Schema", OperationID: "schemaGetApiV1AppsByAppIDDbTablesByTableRows"},
	{Method: "GET", Path: "/api/v1/apps/{appID}/deployments", Tag: "Deploy", OperationID: "deployGetApiV1AppsByAppIDDeployments"},
	{Method: "POST", Path: "/api/v1/apps/{appID}/deployments", Tag: "Deploy", OperationID: "deployPostApiV1AppsByAppIDDeployments"},
	{Method: "GET", Path: "/api/v1/apps/{appID}/deployments/{did}", Tag: "Deploy", OperationID: "deployGetApiV1AppsByAppIDDeploymentsByDid"},
	{Method: "POST", Path: "/api/v1/apps/{appID}/deployments/{did}/cancel", Tag: "Deploy", OperationID: "deployPostApiV1AppsByAppIDDeploymentsByDidCancel"},
	{Method: "POST", Path: "/api/v1/apps/{appID}/deployments/{did}/rollback", Tag: "Deploy", OperationID: "deployPostApiV1AppsByAppIDDeploymentsByDidRollback"},
	{Method: "GET", Path: "/api/v1/apps/{appID}/diagnosis", Tag: "Deploy", OperationID: "deployGetApiV1AppsByAppIDDiagnosis"},
	{Method: "GET", Path: "/api/v1/apps/{appID}/env-vars", Tag: "Apps", OperationID: "appsGetApiV1AppsByAppIDEnvVars"},
	{Method: "POST", Path: "/api/v1/apps/{appID}/env-vars", Tag: "Apps", OperationID: "appsPostApiV1AppsByAppIDEnvVars"},
	{Method: "PUT", Path: "/api/v1/apps/{appID}/env-vars/{key}/staging-value", Tag: "Apps", OperationID: "appsPutApiV1AppsByAppIDEnvVarsByKeyStagingValue"},
	{Method: "DELETE", Path: "/api/v1/apps/{appID}/git-connection", Tag: "Deploy", OperationID: "deployDeleteApiV1AppsByAppIDGitConnection"},
	{Method: "GET", Path: "/api/v1/apps/{appID}/git-connection", Tag: "Deploy", OperationID: "deployGetApiV1AppsByAppIDGitConnection"},
	{Method: "PATCH", Path: "/api/v1/apps/{appID}/git-connection", Tag: "Deploy", OperationID: "deployPatchApiV1AppsByAppIDGitConnection"},
	{Method: "POST", Path: "/api/v1/apps/{appID}/git-connection", Tag: "Deploy", OperationID: "deployPostApiV1AppsByAppIDGitConnection"},
	{Method: "POST", Path: "/api/v1/apps/{appID}/git/github/connect", Tag: "Deploy", OperationID: "deployPostApiV1AppsByAppIDGitGithubConnect"},
	{Method: "GET", Path: "/api/v1/apps/{appID}/git/github/install/start", Tag: "Deploy", OperationID: "deployGetApiV1AppsByAppIDGitGithubInstallStart"},
	{Method: "DELETE", Path: "/api/v1/apps/{appID}/likes", Tag: "Apps", OperationID: "appsDeleteApiV1AppsByAppIDLikes"},
	{Method: "POST", Path: "/api/v1/apps/{appID}/likes", Tag: "Apps", OperationID: "appsPostApiV1AppsByAppIDLikes"},
	{Method: "GET", Path: "/api/v1/apps/{appID}/likes/me", Tag: "Apps", OperationID: "appsGetApiV1AppsByAppIDLikesMe"},
	{Method: "GET", Path: "/api/v1/apps/{appID}/logs", Tag: "Deploy", OperationID: "deployGetApiV1AppsByAppIDLogs"},
	{Method: "POST", Path: "/api/v1/apps/{appID}/oauth-clients", Tag: "Auth", OperationID: "authPostApiV1AppsByAppIDOauthClients"},
	{Method: "POST", Path: "/api/v1/apps/{appID}/promotions/{requestID}/retry", Tag: "Deploy", OperationID: "deployPostApiV1AppsByAppIDPromotionsByRequestIDRetry"},
	{Method: "DELETE", Path: "/api/v1/apps/{appID}/raw-db", Tag: "Apps", OperationID: "appsDeleteApiV1AppsByAppIDRawDb"},
	{Method: "POST", Path: "/api/v1/apps/{appID}/raw-db", Tag: "Apps", OperationID: "appsPostApiV1AppsByAppIDRawDb"},
	{Method: "GET", Path: "/api/v1/apps/{appID}/releases", Tag: "Deploy", OperationID: "deployGetApiV1AppsByAppIDReleases"},
	{Method: "GET", Path: "/api/v1/apps/{appID}/releases/promote-preflight", Tag: "Deploy", OperationID: "deployGetApiV1AppsByAppIDReleasesPromotePreflight"},
	{Method: "DELETE", Path: "/api/v1/apps/{appID}/staging", Tag: "Deploy", OperationID: "deployDeleteApiV1AppsByAppIDStaging"},
	{Method: "PUT", Path: "/api/v1/apps/{appID}/staging", Tag: "Deploy", OperationID: "deployPutApiV1AppsByAppIDStaging"},
	{Method: "GET", Path: "/api/v1/apps/discover", Tag: "Apps", OperationID: "appsGetApiV1AppsDiscover"},
	{Method: "GET", Path: "/api/v1/apps/search", Tag: "Apps", OperationID: "appsGetApiV1AppsSearch"},
	{Method: "DELETE", Path: "/api/v1/comments/{commentID}", Tag: "Apps", OperationID: "appsDeleteApiV1CommentsByCommentID"},
	{Method: "POST", Path: "/api/v1/git/github/complete", Tag: "Deploy", OperationID: "deployPostApiV1GitGithubComplete"},
	{Method: "GET", Path: "/api/v1/github/accounts", Tag: "deploy", OperationID: "deployGetApiV1GithubAccounts"},
	{Method: "GET", Path: "/api/v1/github/installations/{installationID}/repositories", Tag: "deploy", OperationID: "deployGetApiV1GithubInstallationsByInstallationIDRepositories"},
	{Method: "GET", Path: "/api/v1/me", Tag: "Auth", OperationID: "authGetApiV1Me"},
	{Method: "GET", Path: "/api/v1/me/apps/owned", Tag: "Apps", OperationID: "appsGetApiV1MeAppsOwned"},
	{Method: "GET", Path: "/api/v1/me/apps/received", Tag: "Apps", OperationID: "appsGetApiV1MeAppsReceived"},
	{Method: "GET", Path: "/api/v1/me/apps/workspace", Tag: "Apps", OperationID: "appsGetApiV1MeAppsWorkspace"},
	{Method: "GET", Path: "/api/v1/me/personal-access-tokens", Tag: "Schema", OperationID: "schemaGetApiV1MePersonalAccessTokens"},
	{Method: "POST", Path: "/api/v1/me/personal-access-tokens", Tag: "Schema", OperationID: "schemaPostApiV1MePersonalAccessTokens"},
	{Method: "DELETE", Path: "/api/v1/me/personal-access-tokens/{patID}", Tag: "Schema", OperationID: "schemaDeleteApiV1MePersonalAccessTokensByPatID"},
	{Method: "GET", Path: "/api/v1/oauth-clients/{clientID}", Tag: "Auth", OperationID: "authGetApiV1OauthClientsByClientID"},
	{Method: "DELETE", Path: "/api/v1/oauth/clients/{clientID}/grants/me", Tag: "Auth", OperationID: "authDeleteApiV1OauthClientsByClientIDGrantsMe"},
	{Method: "GET", Path: "/api/v1/templates", Tag: "Apps", OperationID: "appsGetApiV1Templates"},
	{Method: "GET", Path: "/api/v1/tenants", Tag: "Tenants", OperationID: "tenantsGetApiV1Tenants"},
	{Method: "GET", Path: "/api/v1/tenants/{tenantID}", Tag: "Tenants", OperationID: "tenantsGetApiV1TenantsByTenantID"},
	{Method: "POST", Path: "/api/v1/tenants/{tenantID}/app-bootstraps", Tag: "Deploy", OperationID: "deployPostApiV1TenantsByTenantIDAppBootstraps"},
	{Method: "GET", Path: "/api/v1/tenants/{tenantID}/app-bootstraps/{bootstrapID}", Tag: "Deploy", OperationID: "deployGetApiV1TenantsByTenantIDAppBootstrapsByBootstrapID"},
	{Method: "GET", Path: "/api/v1/tenants/{tenantID}/apps", Tag: "Apps", OperationID: "appsGetApiV1TenantsByTenantIDApps"},
	{Method: "POST", Path: "/api/v1/tenants/{tenantID}/apps", Tag: "Apps", OperationID: "appsPostApiV1TenantsByTenantIDApps"},
	{Method: "GET", Path: "/api/v1/tenants/{tenantID}/apps/check-availability", Tag: "Apps", OperationID: "appsGetApiV1TenantsByTenantIDAppsCheckAvailability"},
	{Method: "GET", Path: "/api/v1/tenants/{tenantID}/connectors", Tag: "Gateway", OperationID: "gatewayGetApiV1TenantsByTenantIDConnectors"},
	{Method: "GET", Path: "/api/v1/tenants/{tenantID}/connectors/{connectorID}", Tag: "Gateway", OperationID: "gatewayGetApiV1TenantsByTenantIDConnectorsByConnectorID"},
	{Method: "POST", Path: "/api/v1/tenants/{tenantID}/connectors/{connectorID}/discover", Tag: "Gateway", OperationID: "gatewayPostApiV1TenantsByTenantIDConnectorsByConnectorIDDiscover"},
	{Method: "GET", Path: "/api/v1/tenants/{tenantID}/connectors/{connectorID}/resources", Tag: "Gateway", OperationID: "gatewayGetApiV1TenantsByTenantIDConnectorsByConnectorIDResources"},
	{Method: "GET", Path: "/api/v1/tenants/{tenantID}/deployments", Tag: "Deploy", OperationID: "deployGetApiV1TenantsByTenantIDDeployments"},
	{Method: "GET", Path: "/api/v1/tenants/{tenantID}/discover/apps", Tag: "Apps", OperationID: "appsGetApiV1TenantsByTenantIDDiscoverApps"},
	{Method: "POST", Path: "/api/v1/tenants/{tenantID}/gateway/document-invoke", Tag: "Gateway", OperationID: "gatewayPostApiV1TenantsByTenantIDGatewayDocumentInvoke"},
	{Method: "POST", Path: "/api/v1/tenants/{tenantID}/gateway/file-invoke", Tag: "Gateway", OperationID: "gatewayPostApiV1TenantsByTenantIDGatewayFileInvoke"},
	{Method: "POST", Path: "/api/v1/tenants/{tenantID}/gateway/invoke", Tag: "Gateway", OperationID: "gatewayPostApiV1TenantsByTenantIDGatewayInvoke"},
	{Method: "POST", Path: "/api/v1/tenants/{tenantID}/gateway/query", Tag: "Gateway", OperationID: "gatewayPostApiV1TenantsByTenantIDGatewayQuery"},
	{Method: "POST", Path: "/api/v1/tenants/{tenantID}/gateway/sessions", Tag: "Gateway", OperationID: "gatewayPostApiV1TenantsByTenantIDGatewaySessions"},
	{Method: "DELETE", Path: "/api/v1/tenants/{tenantID}/gateway/sessions/{sessionID}", Tag: "Gateway", OperationID: "gatewayDeleteApiV1TenantsByTenantIDGatewaySessionsBySessionID"},
	{Method: "GET", Path: "/api/v1/tenants/{tenantID}/me/connectors", Tag: "Gateway", OperationID: "gatewayGetApiV1TenantsByTenantIDMeConnectors"},
	{Method: "GET", Path: "/api/v1/tenants/{tenantID}/me/connectors/{connectorID}/resources", Tag: "Gateway", OperationID: "gatewayGetApiV1TenantsByTenantIDMeConnectorsByConnectorIDResources"},
	{Method: "GET", Path: "/api/v1/tenants/{tenantID}/me/grants", Tag: "Authorization", OperationID: "authorizationGetApiV1TenantsByTenantIDMeGrants"},
	{Method: "GET", Path: "/api/v1/users/me/apps", Tag: "Apps", OperationID: "appsGetApiV1UsersMeApps"},
	{Method: "POST", Path: "/auth/logout", Tag: "Auth", OperationID: "authPostAuthLogout"},
	{Method: "POST", Path: "/auth/refresh", Tag: "Auth", OperationID: "authPostAuthRefresh"},
	{Method: "GET", Path: "/config/public", Tag: "Config", OperationID: "configGetConfigPublic"},
	{Method: "GET", Path: "/oauth/google/callback", Tag: "Gateway", OperationID: "gatewayGetOauthGoogleCallback"},
	{Method: "GET", Path: "/oauth/userinfo", Tag: "Auth", OperationID: "authGetOauthUserinfo"},
}

var routeByOperation = func() map[string]Route {
	m := make(map[string]Route, len(Routes))
	for _, r := range Routes {
		m[r.OperationID] = r
	}
	return m
}()
